FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04

# CUDA includes
ENV CUDA_PATH /usr/local/cuda
ENV CUDA_INCLUDE_PATH /usr/local/cuda/include
ENV CUDA_LIBRARY_PATH /usr/local/cuda/lib64

RUN echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

ENV CUDNN_VERSION 6.0.20
RUN apt-get update && apt-get install -y --allow-unauthenticated --no-install-recommends \
         build-essential \
         software-properties-common \
         apt-utils \
         cmake \
         git \
         curl \
         wget \
         vim \
         unzip \
         openssh-client \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \
         libsm6 \
         libosmesa-dev \
         libgl1-mesa-dev \
         libxext6 \
         libglfw3-dev \ 
         libxrender-dev \
         libcudnn6=$CUDNN_VERSION-1+cuda8.0 \
         libcudnn6-dev=$CUDNN_VERSION-1+cuda8.0 && \
     rm -rf /var/lib/apt/lists/*

RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install conda-build && \
     /opt/conda/bin/conda create -y --name tf-py35 python=3.5.2 numpy pyyaml scipy ipython mkl patchelf&& \
     /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/envs/tf-py35/bin:$PATH

RUN pip install gym tensorflow matplotlib GitPython cython lockfile glfw imageio gym[mujoco] cffi
RUN git clone https://github.com/openai/baselines.git && cd baselines && git checkout ab59de69223c25754252efc024edd2bb92edd8e2 && pip install -e .

ENV MUJOCO_PY_MJKEY_PATH /.mujoco/mjkey.txt
ENV MUJOCO_PY_MUJOCO_PATH /.mujoco/mujoco200_linux

WORKDIR /

RUN wget https://www.roboti.us/download/mujoco200_linux.zip -O mujoco.zip \
    && unzip mujoco.zip -d /.mujoco \
    && rm mujoco.zip && ls -la /.mujoco

COPY ./mjkey.txt /.mujoco/mjkey.txt
ENV LD_LIBRARY_PATH /.mujoco/mujoco200_linux/bin:${LD_LIBRARY_PATH}
RUN pip install mujoco-py


RUN chmod -R 777 /opt/conda/envs/tf-py35/lib/python3.5/site-packages/
RUN useradd -d /project -u <<UID>> --create-home user 
USER user
WORKDIR /project/
ADD . /project/

# Section to get permissions right, and avoid running inside as root {{
# Create a user matching the UID, and create/chmod home dir (== user directory)
# (uid corresponds to breord in CS network)
# }}
ENV PYTHONPATH "$PYTHONPATH:/project/"

RUN export PATH=$PATH:$HOME/.local/bin
COPY ./mjkey.txt /project/.mujoco/mjkey.txt
ENV LD_LIBRARY_PATH /project/.mujoco/mjpro200_linux/bin:${LD_LIBRARY_PATH}